[package]
name = "http"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]

fl-wasm-rs = { path = "../../fl-wasm-rs" }
serde_json = "1.0.85"
serde = { version = "1.0.145", features = ["derive"] }
