name: fl-wasm-rs

on:
  push:
    branches: [main]
    paths:
      - "./rust/fl-wasm-rs/**"
    tags:
      - "v*"
  pull_request:
    branches: [main]
    paths:
      - "./rust/fl-wasm-rs/**"

env:
  CARGO_TERM_COLOR: always
  working-directory: ./rust/fl-wasm-rs

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: clippy & fmt
        working-directory: ${{ env.working-directory }}
        run: |
          cargo clippy --all-features --all-targets
          rustfmt --edition 2021 --check src/*.rs

  github_release:
    if: startswith(github.ref, 'refs/tags/') # Only run on tag push
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: true
